# Generated by Django 3.0.4 on 2020-05-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Cod_Cate', models.AutoField(primary_key=True, serialize=False)),
                ('nomecategoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contenuto',
            fields=[
                ('Cod_Cont', models.AutoField(primary_key=True, serialize=False)),
                ('testo', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('approvato', models.IntegerField()),
                ('estrazioni', models.IntegerField()),
                ('Cod_Cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomwords.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('Cod_Utente', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=30)),
                ('descrizione', models.CharField(max_length=200)),
                ('permesso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessione',
            fields=[
                ('Cod_Sessio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('timestamp_post', models.IntegerField()),
                ('Cod_Utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomwords.Utente')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('Cod_Like', models.AutoField(primary_key=True, serialize=False)),
                ('Cod_Cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomwords.Contenuto')),
                ('Cod_Utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomwords.Utente')),
            ],
        ),
        migrations.AddField(
            model_name='contenuto',
            name='Cod_Utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomwords.Utente'),
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('Cod_Com', models.AutoField(primary_key=True, serialize=False)),
                ('testo', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('Cod_Cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomwords.Contenuto')),
                ('Cod_Utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomwords.Utente')),
            ],
        ),
    ]
