# Generated by Django 3.0.4 on 2020-05-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenuto',
            name='titolo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
