# Generated by Django 3.0.4 on 2020-05-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomwords', '0002_contenuto_titolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenuto',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
