# Generated by Django 3.0.4 on 2020-05-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomwords', '0003_auto_20200508_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commento',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
