# Generated by Django 3.0.4 on 2020-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomwords', '0006_giorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giorno',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
