# Generated by Django 3.0.4 on 2020-05-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomwords', '0007_auto_20200515_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giorno',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
