# Generated by Django 3.0.4 on 2020-05-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomwords', '0008_auto_20200515_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessione',
            name='ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
