# Generated by Django 3.0.4 on 2020-05-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomwords', '0010_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='codice',
        ),
    ]
