# Generated by Django 3.0.4 on 2020-05-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomwords', '0011_auto_20200522_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='Cod_Utente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='randomwords.Utente'),
        ),
    ]
