# Generated by Django 3.0.4 on 2020-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomwords', '0012_token_cod_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='verificato',
            field=models.IntegerField(default=0),
        ),
    ]
